//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Farm_2._0_Edition
{
    using System;
    using System.Collections.Generic;
    
    public partial class Horses
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Horses()
        {
            this.Trading = new HashSet<Trading>();
        }
    
        public int idHorse { get; set; }
        public string HorseName { get; set; }
        public string HorseAge { get; set; }
        public string HorseGender { get; set; }
        public string HorseBreed { get; set; }
        public Nullable<int> idStaff { get; set; }
        public Nullable<int> idSellingStatus { get; set; }
        public Nullable<int> idCompetitionStatus { get; set; }
        public byte[] Photo { get; set; }
    
        public virtual Competition Competition { get; set; }
        public virtual SellingStatus SellingStatus { get; set; }
        public virtual Staff Staff { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Trading> Trading { get; set; }
    }
}
