//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Farm_2._0_Edition
{
    using System;
    using System.Collections.Generic;
    
    public partial class SellingStatus
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SellingStatus()
        {
            this.Horses = new HashSet<Horses>();
        }
    
        public int idSellingStatus { get; set; }
        public string SellingStatusName { get; set; }
        public string idTrade { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Horses> Horses { get; set; }
        public virtual Trading Trading { get; set; }
    }
}
