//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Farm_2._0_Edition
{
    using System;
    using System.Collections.Generic;
    
    public partial class Trading
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Trading()
        {
            this.SellingStatus = new HashSet<SellingStatus>();
        }
    
        public string idTrade { get; set; }
        public System.DateTime TradeDateTime { get; set; }
        public int idStaff { get; set; }
        public string Price { get; set; }
        public int idHorse { get; set; }
        public Nullable<int> StaffID { get; set; }
    
        public virtual Horses Horses { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SellingStatus> SellingStatus { get; set; }
        public virtual Staff Staff { get; set; }
        public virtual Staff Staff1 { get; set; }
    }
}
